# -*- coding: utf-8 -*-
"""getPostAPIs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubz2u87Lp7s0JD4ObnQewVo4Q2FeFlkE
"""

import requests

BASE_URL = "https://api.jsonbin.io/v3/b"
HEADERS = {
    "Content-Type": "application/json",
    "X-Master-Key": "$2a$10$3e3onxuWlqlr2ULMNUWjhegjvBOhs/XbRE6Zj5VQ8/RWai7zmxURm"
}

# Hacer una petición GET para obtener un bin por ID
def get_post_by_id(bin_id):
    url = f"{BASE_URL}/{bin_id}"
    response = requests.get(url, headers=HEADERS)
    if response.status_code == 200:
        return response.json()
    else:
        return f"Error: {response.status_code}, {response.text}"

# Petición POST para crear un bin
def create_post(title, body, user_id):
    data = {"title": title, "body": body, "userId": user_id}
    response = requests.post(BASE_URL, json=data, headers=HEADERS)
    if response.status_code == 200:
        return response.json()
    else:
        return f"Error: {response.status_code}, {response.text}"

# Ejemplo
if __name__ == "__main__":
    print("\nCreando un nuevo post en JSONBin...")
    new_post = create_post("Mi nuevo post en JSONBin noo", "Este post está almacenado en la nube", 1)
    print(new_post)

    if "metadata" in new_post:
        bin_id = new_post["metadata"]["id"]
        print("\nObteniendo el post guardado en JSONBin...")
        retrieved_post = get_post_by_id(bin_id)
        print(retrieved_post)

!pip install requests